import {
    Layers,
    Scissors,
    RotateCw,
    LayoutGrid,
    Image,
    FileImage,
    FileText,
    FileType,
    Table,
    Sheet,
    Droplets,
    Hash,
    Trash2,
    FileOutput,
    Type,
    PenTool,
    Edit3,
    Lock,
    Unlock,
    Minimize2,
    Wrench,
    Presentation,
    ScanText,
    Camera,
    Eraser,
    LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
    Layers,
    Scissors,
    RotateCw,
    LayoutGrid,
    Image,
    FileImage,
    FileText,
    FileType,
    Table,
    Sheet,
    Droplets,
    Hash,
    Trash2,
    FileOutput,
    Type,
    PenTool,
    Edit3,
    Lock,
    Unlock,
    Minimize2,
    Wrench,
    Presentation,
    ScanText,
    Camera,
    Eraser,
};

export function getToolIcon(iconName: string): LucideIcon {
    return ICON_MAP[iconName] || FileText;
}
